# Assignment-3 on NumPy for AI/ML

**Name:** Varshini Priya  
**Roll No:** 238T1A0555

## Section A – Conceptual Understanding

### A1. Why are NumPy arrays generally preferred over plain Python lists for numerical computation in AI/ML workloads?

NumPy arrays are generally preferred because they are faster and more efficient for numerical calculations. They use less memory than Python lists for storing numerical data. NumPy also provides many mathematical operations and supports vectorized operations, which makes working with large datasets easier and faster.

### A2. Explain vectorization. Why does replacing an explicit Python loop with a vectorized NumPy operation matter with large datasets?

Vectorization means performing an operation on an entire NumPy array at once instead of using a Python loop for each element. It makes numerical operations faster and more efficient. For large datasets, vectorization reduces execution time and makes the code simpler and easier to work with.

### A3. For compatible 2D arrays A and B, explain A * B vs A @ B. Describe one neural-network situation for each.

A * B performs element-wise multiplication, where corresponding elements of the two arrays are multiplied. A @ B performs matrix multiplication, where rows of A are multiplied with columns of B. In a neural network, A * B can be used for element-wise operations on values, while A @ B can be used to multiply an input matrix by a weight matrix.

### A4. What is broadcasting in NumPy? State the general rule used to decide whether arrays of different shapes can be combined element-wise?

Broadcasting is a NumPy feature that allows arrays with different shapes to be used together in element-wise operations. NumPy compares their shapes from the last dimension to the first. Two dimensions are compatible when they are equal or when one of them is 1. If the dimensions are not compatible, NumPy gives a broadcasting error.

### A5. Explain flatten() vs ravel(). In a memory-constrained application processing large images, which would you prefer and why?

The flatten() function converts an array into a one-dimensional copy, so changes to the new array do not affect the original array. The ravel() function also converts an array into one dimension, but it usually returns a view of the original array when possible. For a memory-constrained application processing large images, I would prefer ravel() because it can avoid creating an extra copy and therefore use less memory.

### A6. For a 2D array, explain axis=0 and axis=1 in an aggregation function such as np.sum() or np.mean(). Illustrate with a small example.

For a 2D array, axis=0 means the operation is performed down the rows, giving a result for each column. Axis=1 means the operation is performed across the columns, giving a result for each row. For example, for [[1, 2], [3, 4]], np.sum(array, axis=0) gives [4, 6], while np.sum(array, axis=1) gives [3, 7].

### A7. Why is it important to normalize or standardize numerical features before training most ML models? Explain normalization vs standardization.

Normalization or standardization helps put numerical features on a similar scale. This can help machine learning models learn more effectively when different features have very different ranges. Normalization usually scales values to a fixed range such as 0 to 1, while standardization transforms values so that they have a mean of 0 and a standard deviation of 1.

### A8. Why do functions such as np.nanmean() exist? What happens if np.mean() is used directly on data containing NaN?

Functions such as np.nanmean() are useful when data contains missing values represented by NaN. np.nanmean() calculates the mean while ignoring the NaN values. If np.mean() is used directly on data containing NaN, the result will normally be NaN.

### A9. In the ML convention X.shape = (samples, features), explain how this extends to a batch of RGB images. Write the exact shape for 64 RGB images of size 128 × 128.

For a batch of RGB images, the shape includes the number of images, height, width, and color channels. Therefore, 64 RGB images of size 128 × 128 have the shape (64, 128, 128, 3). Here, 64 represents the number of images, 128 and 128 represent the height and width, and 3 represents the RGB color channels.

### A10. Why is reproducibility important during model development and experimentation? Refer to fixing a random seed with np.random.default_rng(seed).

Reproducibility is important because it helps us get the same random results when we repeat an experiment. This makes it easier to test, compare, and debug machine learning models. Using np.random.default_rng(seed) with a fixed seed makes the random number generation repeatable.

## Section B – Predict the Output


### B1. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    a = np.array([1, 2, 3])
    b = np.array([[1], [2], [3]])
    print((a + b).shape)

**Predicted Output:**

    (3, 3)

**Explanation:** NumPy broadcasts the arrays with shapes `(3,)` and `(3, 1)`, resulting in an array with shape `(3, 3)`.

### B2. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    x = np.arange(1, 7).reshape(2, 3)
    print(x[:, 1])

**Predicted Output:**

    [2 5]

**Explanation:** `x[:, 1]` selects all rows from the second column of the array, so the output is `[2 5]`.

### B3. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    arr = np.array([5, 10, 15, 20, 25])
    print(arr[arr % 10 == 0])

**Predicted Output:**

    [10 20]

**Explanation:** `arr % 10 == 0` checks which elements are divisible by 10. The elements `10` and `20` satisfy the condition, so the output is `[10 20]`.

### B4. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    m = np.array([[1, 2], [3, 4]])
    print(m.T @ m)

**Predicted Output:**

    [[10 14]
     [14 20]]

**Explanation:** `m.T` is the transpose of `m`, and `@` performs matrix multiplication between `m.T` and `m`, giving the result shown above.

### B5. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    data = np.array([1, 2, np.nan, 4])
    print(np.mean(data), np.nanmean(data))

**Predicted Output:**

    nan 2.3333333333333335

**Explanation:** `np.mean()` returns `nan` because the array contains a NaN value, while `np.nanmean()` ignores the NaN and calculates the mean of the remaining values.

### B6. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    x = np.array([10, 20, 30])
    y = np.where(x > 15, 1, 0)
    print(y)

**Predicted Output:**

    [0 1 1]

**Explanation:** `np.where()` gives `1` when the value is greater than 15 and `0` otherwise, so the output is `[0 1 1]`.

### B7. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    a = np.zeros((3, 4))
    print(a.ndim, a.size)

**Predicted Output:**

    2 12

**Explanation:** The array has 2 dimensions and contains 12 elements because it has 3 rows and 4 columns.

### B8. Predict the exact output and/or resulting shape. Justify in one sentence.

**Code:**

    arr = np.arange(1, 13).reshape(3, 4)
    print(arr[::-1, ::-1])

**Predicted Output:**

    [[12 11 10  9]
     [ 8  7  6  5]
     [ 4  3  2  1]]

**Explanation:** `[::-1, ::-1]` reverses the order of both the rows and columns, so the entire array is reversed.

## Section C – Coding / Implementation

### C1. Given a 1D NumPy array of exam scores, use `np.where()` to produce labels 'P' (score >= 40) or 'F' (score < 40). 

In [2]:
import numpy as np

scores = np.array([35, 42, 67, 28, 90, 39, 55])

labels = np.where(scores >= 40, "P", "F")

print("Scores:", scores)
print("Labels:", labels)

Scores: [35 42 67 28 90 39 55]
Labels: ['F' 'P' 'P' 'F' 'P' 'F' 'P']


**Explanation:** `np.where()` assigns "P" to scores greater than or equal to 40 and "F" to scores below 40.

### C2. Write a function `standardize(x)` that takes a 1D NumPy array and returns its z-score standardized version using only NumPy. 

In [3]:
import numpy as np

def standardize(x):
    return (x - np.mean(x)) / np.std(x)

x = np.array([10, 20, 30, 40, 50])

result = standardize(x)

print("Standardized values:", result)

Standardized values: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


**Explanation:** The function standardizes the values by subtracting the mean and dividing by the standard deviation.

### C3. Given two 2D NumPy arrays representing separate batches with the same number of features, combine them using an appropriate NumPy stacking function and print the resulting shape. 

In [4]:
import numpy as np

batch1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

batch2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

combined = np.vstack((batch1, batch2))

print("Combined shape:", combined.shape)

Combined shape: (4, 3)


**Explanation:** `np.vstack()` combines the two batches vertically because they have the same number of features (3 columns), resulting in a shape of `(4, 3)`.

### C4. Given X with shape (100, 5), compute column-wise mean and standard deviation and standardize the matrix in one vectorized expression.

In [5]:
import numpy as np

X = np.random.default_rng(42).normal(size=(100, 5))

mean = np.mean(X, axis=0)
std = np.std(X, axis=0)

X_standardized = (X - mean) / std

print("Mean:", mean)
print("Standard deviation:", std)
print("Standardized shape:", X_standardized.shape)

Mean: [-0.02976502 -0.0243285   0.02132587  0.00977781 -0.04264091]
Standard deviation: [0.93907585 0.86849238 0.94883911 1.05055432 0.97727443]
Standardized shape: (100, 5)


**Explanation:** The columns are standardized using `(X - mean) / std`, where the mean and standard deviation are calculated column-wise with `axis=0`.

### C5. Implement `y_pred = X @ w + b` for a feature matrix X, weight vector w and bias b. Then compute MSE using y_true.

In [6]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])
b = 2.0

y_true = np.array([4, 5, 6])

y_pred = X @ w + b

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 1.1666666666666667


**Explanation:** The model prediction is calculated using `X @ w + b`, and MSE is calculated as the mean of the squared differences between `y_true` and `y_pred`.

### C6. Using `np.random.default_rng()` with a fixed seed, generate 10 samples and 3 features from a normal distribution. Print the shape and confirm identical results with the same seed.

In [7]:
import numpy as np

rng1 = np.random.default_rng(42)
data1 = rng1.normal(size=(10, 3))

rng2 = np.random.default_rng(42)
data2 = rng2.normal(size=(10, 3))

print("Shape:", data1.shape)
print("Identical results:", np.array_equal(data1, data2))

Shape: (10, 3)
Identical results: True


**Explanation:** Using the same fixed seed produces the same random values, so both generated arrays are identical.

### C7. Given a grayscale image as a 2D NumPy array with pixel values in [0, 255], normalize the values to [0, 1] using min-max normalization.

In [8]:
import numpy as np

image = np.array([[0, 64, 128],
                  [192, 255, 100]])

normalized = (image - image.min()) / (image.max() - image.min())

print("Normalized image:")
print(normalized)

Normalized image:
[[0.         0.25098039 0.50196078]
 [0.75294118 1.         0.39215686]]


**Explanation:** Min-max normalization scales the pixel values from the range [0, 255] to the range [0, 1].

### C8. Given 4 RGB images of shape `(28, 28, 3)`, stored as shape `(4, 28, 28, 3)`, compute the average pixel value of each image across height, width and channels. State the axis argument and why.

In [9]:
import numpy as np

images = np.random.default_rng(42).integers(0, 256, size=(4, 28, 28, 3))

average_pixels = np.mean(images, axis=(1, 2, 3))

print("Average pixel value of each image:")
print(average_pixels)
print("Shape:", average_pixels.shape)

Average pixel value of each image:
[127.56505102 126.25212585 125.75722789 126.9914966 ]
Shape: (4,)


**Explanation:** Axes `(1, 2, 3)` represent height, width, and RGB channels, so averaging across them gives one average pixel value for each of the 4 images.

## Section D – Applied / Scenario-Based Problems

### D1. Data Preprocessing Pipeline 

You are given a raw 1D or 2D NumPy array containing NaN values.

Describe, step by step, the NumPy operations you would apply to:

(a) detect missing values,

(b) handle them appropriately and justify your strategy, and

(c) normalize or standardize the clean data before it is fed to a model.

Implement the full pipeline in code on a sample array of your own choosing, including at least one NaN.

In [13]:
import numpy as np

data = np.array([10.0, 20.0, np.nan, 40.0, 50.0])

# (a) Detect missing values
missing = np.isnan(data)
print("Missing values:", missing)

# (b) Handle missing value
clean_data = np.nan_to_num(data, nan=np.nanmean(data))
print("Clean data:", clean_data)

# (c) Standardize the clean data
mean = np.mean(clean_data)
std = np.std(clean_data)

standardized = (clean_data - mean) / std

print("Standardized data:", standardized)

Missing values: [False False  True False False]
Clean data: [10. 20. 30. 40. 50.]
Standardized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


**Explanation:** `np.isnan()` detects the missing value, `np.nanmean()` replaces it with the mean of the available values, and the clean data is standardized using its mean and standard deviation.

### D2. Image Batch Understanding 

1.Explain, with correct NumPy shapes, how a single RGB image differs from a batch of RGB images.

2.Write code to create a dummy batch of 16 images of size 64 × 64 using random pixel values.

3.Compute the average image of the batch, meaning the element-wise mean across all 16 images.

4.State the shape of your result and explain why.

**1. Single RGB image vs batch:** A single RGB image has the shape `(64, 64, 3)`, where 64 represents height, 64 represents width, and 3 represents the RGB channels. A batch of 16 RGB images has the shape `(16, 64, 64, 3)`, where 16 represents the number of images.

**2. Dummy batch:** A dummy batch of 16 images can be created using NumPy random pixel values with the shape `(16, 64, 64, 3)`.

**3. Average image:** The average image is calculated by taking the element-wise mean across all 16 images using `np.mean(images, axis=0)`.

**4. Result shape:** The result has the shape `(64, 64, 3)` because `axis=0` averages the 16 images while keeping the height, width, and RGB channel dimensions.

In [14]:
import numpy as np

images = np.random.default_rng(42).integers(
    0, 256, size=(16, 64, 64, 3)
)

average_image = np.mean(images, axis=0)

print("Batch shape:", images.shape)
print("Average image shape:", average_image.shape)

Batch shape: (16, 64, 64, 3)
Average image shape: (64, 64, 3)


### D3. Debug the Model Code 

The following code contains more than one bug:

```python
X = np.array([[1, 2],
              [2, 3],
              [3, 4]])  # shape (3, 2)
w = np.array([0.5, 1.0, 0.2])  # intended weight vector
b = 2.0
y_pred = X @ w + b
y_true = np.array([10, 20, 30])
mse = np.mean(y_true - y_pred ** 2)

### Bug 1 – Weight Vector Shape

`X` has shape `(3, 2)`, so `w` should contain 2 values. But `w` contains 3 values, causing a shape mismatch in `X @ w`.

### Bug 2 – MSE Calculation

`y_true - y_pred ** 2` is incorrect because `y_pred ** 2` is calculated first. The correct expression is `(y_true - y_pred) ** 2`.

In [15]:
import numpy as np

X = np.array([[1, 2],
              [2, 3],
              [3, 4]])

w = np.array([0.5, 1.0])

b = 2.0

y_pred = X @ w + b

y_true = np.array([10, 20, 30])

mse = np.mean((y_true - y_pred) ** 2)

print("Predicted values:", y_pred)
print("MSE:", mse)

Predicted values: [4.5 6.  7.5]
MSE: 244.16666666666666


**Explanation:** The corrected code uses 2 weights for the 2 features in `X` and calculates MSE by first finding the prediction error, then squaring it, and finally taking the mean.

## Section E – Bonus / Challenge

### E1. Per-Column Min–Max Normalization 

Implement min-max normalization for a 2D feature matrix on a per-column (per-feature) basis, rather than using a single global min/max for the whole array. Your solution must be fully vectorized, with no explicit loops over rows or columns.

**Explanation:** Per-column min-max normalization scales each feature separately to the range `[0, 1]` using the minimum and maximum values of that column.

In [16]:
import numpy as np

X = np.array([[10, 100],
              [20, 200],
              [30, 300]])

min_values = np.min(X, axis=0)
max_values = np.max(X, axis=0)

normalized = (X - min_values) / (max_values - min_values)

print("Original data:")
print(X)

print("Normalized data:")
print(normalized)

Original data:
[[ 10 100]
 [ 20 200]
 [ 30 300]]
Normalized data:
[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


**Explanation:** Each column is normalized separately using its own minimum and maximum values, and no explicit loops are used.

### E2. Three-Level Score Classification [5 marks]

Given a 1D array of exam scores, use a single vectorized expression (no if/else statements and no explicit loops) to classify each score as:

Fail (< 40), Average (40–70 inclusive), or Excellent (> 70).

Hint: You may need to nest or combine np.where() calls.

**Explanation:** The scores are classified into Fail, Average, or Excellent using `np.where()` without loops or if/else statements.

In [17]:
import numpy as np

scores = np.array([25, 40, 55, 70, 85, 95])

result = np.where(scores < 40, "Fail",
                  np.where(scores <= 70, "Average", "Excellent"))

print("Scores:", scores)
print("Classification:", result)

Scores: [25 40 55 70 85 95]
Classification: ['Fail' 'Average' 'Average' 'Average' 'Excellent' 'Excellent']


**Explanation:** Each score is classified as Fail, Average, or Excellent using `np.where()`.